// <auto-generated />
namespace Bonafide.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pp3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pp3));
        
        string IMigrationMetadata.Id
        {
            get { return "201611221130099_pp3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
